# Workflow name as displayed in GitHub Actions UI
name: Test Frontend

on:
  workflow_call:

jobs:
  test: 
      runs-on: self-hosted  # Use Ubuntu as the runner OS
      steps:
        # Step 1: Check out the repository code
        - uses: actions/checkout@v3  # Official action to clone repo
        
        # Step 2: Set up Node.js environment
        - name: Setup Node
          uses: actions/setup-node@v3  # Official Node.js setup action
          with:
            node-version: 18   # Specify Node.js version
        
        # Step 3: Install dependencies and run tests
        - name: Install and Test
          run: |
            cd frontend       # Navigate to Frontend directory
            npm install       # Install dependencies
            npm test          # Run tests